;;; Bootstrap straight.el (package manager)
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;;; use-package, wired up to straight.el
(straight-use-package 'use-package)
;; Be explicit: each use-package block opts in with `:straight t' rather
;; than straight trying (and sometimes failing) to fetch a recipe for
;; every built-in Emacs feature we merely want to configure.
(setq straight-use-package-by-default nil)
(setq use-package-always-defer nil)

(use-package diminish :straight t)

(use-package exec-path-from-shell
  :straight t
  :if (memq window-system '(mac ns))
  :init (exec-path-from-shell-initialize))

(use-package autorevert
  :diminish auto-revert-mode
  :config (global-auto-revert-mode))

;;; Load one file per concern from customizations/
(dolist (file (directory-files
               (expand-file-name "customizations" user-emacs-directory)
               t "^[^#].*\\.el\\'"))
  (load file nil 'nomessage))

;;; Custom (auto-generated by Emacs' Customize UI) lives in its own file
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(load custom-file 'noerror 'nomessage)
